name       : vnstat
version    : 1.16
release    : 1
source     :
    - https://github.com/vergoh/vnstat/archive/v1.16.tar.gz : 66746c3e982e0e29491028b4d1d87f56fd5383899124a917e8a3fd501acbb14c
license    : GPL-3.0
component  : system.utils
summary    : A network traffic monitor for Linux and BSD
description: |
    vnStat is a console-based network traffic monitor that uses the network interface statistics
    provided by the kernel as information source. This means that vnStat will not actually be
    sniffing any traffic and also ensures light use of system resources.
    Traffic statistics are stored on a hourly level for the last 24 hours, on a daily level for the
    last 30 days and on a monthly level for the last 12 months. Total seen traffic and a top 10
    days listing is also provided.
builddeps  :
    - pkgconfig(gdlib)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
