name       : vnstat
version    : '2.8'
release    : 9
source     :
    - https://github.com/vergoh/vnstat/releases/download/v2.8/vnstat-2.8.tar.gz : 03f858a7abf6bd85bb8cd595f3541fc3bd31f8f400ec092ef3034825ccb77c25
license    : GPL-2.0-or-later
component  : system.utils
summary    : A network traffic monitor for Linux and BSD
description: |
    vnStat is a console-based network traffic monitor that uses the network interface statistics provided by the kernel as information source. This means that vnStat will not actually be sniffing any traffic and also ensures light use of system resources. Traffic statistics are stored on a hourly level for the last 24 hours, on a daily level for the last 30 days and on a monthly level for the last 12 months. Total seen traffic and a top 10 days listing is also provided.
builddeps  :
    - pkgconfig(gdlib)
    - pkgconfig(sqlite3)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 examples/systemd/vnstat.service $installdir/%libdir%/systemd/system/vnstat.service
